### ISSUE TITLE
デプロイのためにアプリをビルドする

### ISSUE THREAD

**Issue by AyumuOgasawara** [AyumuOgasawara/receipt-scanner#117]
npm rn buildとnpm run startをできるようにする

**Comment by AyumuOgasawara** [comment]
出てきたwarningとerror

``` sh
./src/_components/features/budgets/BudgetsTable.tsx
47:6  Warning: React Hook useEffect has a missing dependency: 'getAndSetCategoryBudgets'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./src/_components/features/dashboard/LowerDashboard.tsx
5:23  Error: 'red' is defined but never used.  @typescript-eslint/no-unused-vars

./src/_components/features/expenses/ExpenseDialog.tsx
3:32  Error: 'useRef' is defined but never used.  @typescript-eslint/no-unused-vars
89:6  Warning: React Hook useEffect has a missing dependency: 'validateFields'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
100:6  Warning: React Hook useEffect has a missing dependency: 'getReceiptImage'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
100:7  Warning: React Hook useEffect has a complex expression in the dependency array. Extract it to a separate variable so it can be statically checked.  react-hooks/exhaustive-deps
164:21  Error: Expected an assignment or function call and instead saw an expression.  @typescript-eslint/no-unused-expressions

./src/_components/features/expenses/ExpensesTable.tsx
54:6  Warning: React Hook useEffect has a missing dependency: 'getExpensesAndSetRows'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./src/_components/features/expenses/ShowReceipt.tsx
32:15  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
32:15  Warning: img elements must have an alt prop, either with meaningful text, or an empty string for decorative images.  jsx-a11y/alt-text

./src/_components/features/sidebar/AddExpenseDetail.tsx
61:6  Warning: React Hook useEffect has a missing dependency: 'validateFields'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
76:15  Error: Expected an assignment or function call and instead saw an expression.  @typescript-eslint/no-unused-expressions

./src/_components/features/sidebar/ReceiptUpload.tsx
33:13  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
33:13  Warning: img elements must have an alt prop, either with meaningful text, or an empty string for decorative images.  jsx-a11y/alt-text

./src/_components/features/sidebar/Sidebar.tsx
76:36  Error: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
82:36  Error: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
105:6  Warning: React Hook useEffect has missing dependencies: 'pathname', 'router', and 'selectedDate'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps

./src/_components/features/sidebar/SidebarServer.ts
20:9  Error: 'currentDate' is never reassigned. Use 'const' instead.  prefer-const

./src/lib/db/expense.ts
10:10  Error: 'da' is defined but never used.  @typescript-eslint/no-unused-vars

./src/types/next-auth.d.ts
2:31  Error: 'Session' is defined but never used.  @typescript-eslint/no-unused-vars
2:40  Error: 'User' is defined but never used.  @typescript-eslint/no-unused-vars
3:15  Error: 'JWT' is defined but never used.  @typescript-eslint/no-unused-vars

```

**Comment by AyumuOgasawara** [comment]
とりあえず、errorのκみに対応していく。
`is defined but never used.`は使われていないものを削除していった。

**Comment by AyumuOgasawara** [comment]
`164:21  Error: Expected an assignment or function call and instead saw an expression. `

該当場所
----
``` tsx
<DatePicker
                  label="日付"
                  value={dayjs(expenseDate)}
                  onChange={(newValue) => {
                    newValue ? setExpenseDate(newValue.toDate()) : null;
                  }}
                  slotProps={{
                    calendarHeader: {
                      format: "YYYY年MM月", // カレンダーの年月の部分
                    },
                    textField: {
                      variant: "filled",
                    },
                  }}
                  format="YYYY年MM月DD" // 入力欄
                />
```



三項演算子を使っているが、nullが定義されているためよくないとのこと

以下のように修正

``` tsx
<DatePicker
                  label="日付"
                  value={dayjs(expenseDate)}
                  onChange={(newValue) => {
                    newValue && setExpenseDate(newValue.toDate());
                  }}
                  slotProps={{
                    calendarHeader: {
                      format: "YYYY年MM月", // カレンダーの年月の部分
                    },
                    textField: {
                      variant: "filled",
                    },
                  }}
                  format="YYYY年MM月DD" // 入力欄
                />
```

**Comment by AyumuOgasawara** [comment]
`76:36  Error: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any`

## 該当箇所
---------
``` tsx
  const handleDateChange = (event: any) => {
    setSelectedDate(event.target.value);
    router.push(pathname + "?date=" + event.target.value);
  };
```

anyを使っているから怒られている。

{SelectChangeEvent,} from "@mui/material";を使用し、以下のように修正

``` tsx
const handleDateChange = (event: SelectChangeEvent<string>) => {
    setSelectedDate(event.target.value);
    router.push(pathname + "?date=" + event.target.value);
  };
```

**Comment by AyumuOgasawara** [comment]
``` sh
./src/types/next-auth.d.ts
2:31  Error: 'Session' is defined but never used.  @typescript-eslint/no-unused-vars
2:40  Error: 'User' is defined but never used.  @typescript-eslint/no-unused-vars
3:15  Error: 'JWT' is defined but never used.  @typescript-eslint/no-unused-vars
```

以上のように怒られているが、これらを削除したら、auth.tsのsession.user.id = token.id;の部分で、Type error: Type 'unknown' is not assignable to type 'string'.と怒られた。

## src/types/next-auth.d.ts
``` ts
import "next-auth";
import type { DefaultSession, Session, User } from "next-auth";
import type { JWT } from "next-auth/jwt";

type UserId = string;

declare module "next-auth/jwt" {
  interface JWT {
    id: UserId;
  }
}

declare module "next-auth" {
  interface Session {
    user: DefaultSession["user"] & {
      id: UserId;
    };
  }
}
```

## src/auth.ts
``` ts
import NextAuth from "next-auth";
import { authConfig } from "@/lib/auth.config";
import { PrismaAdapter } from "@auth/prisma-adapter";
import {
  createUserAction,
  fetchUserWithEmailAction,
} from "@/app/_actions/users";
import prisma from "@/lib/prisma";

export const { handlers, signIn, signOut, auth } = NextAuth({
  ...authConfig,
  adapter: PrismaAdapter(prisma),
  session: {
    strategy: "jwt",
  },
  pages: {
    signIn: "/",
  },
  callbacks: {
    async jwt({ token, user }) {
      if (user) {
        const dbUser = await fetchUserWithEmailAction(user?.email || "");

        if (!dbUser) {
          const res = await createUserAction({
            name: user.name!,
            email: user.email!,
            image: user.image!,
          });
          token.id = res.id;
          return token;
        }

        token.id = dbUser.id;
        token.name = dbUser.name;
        token.email = dbUser.email;
        token.picture = dbUser.image;
      }

      return token;
    },

    async session({ session, token }) {
      if (token) {
        session.user.id = token.id;
        session.user.name = token.name;
        session.user.email = token.email!;
        session.user.image = token.picture;
      }
      return session;
    },

    redirect() {
      return "/";
    },
  },
});
```

**Comment by AyumuOgasawara** [comment]
よって、 as stringをつけて、明示することにした。
``` ts
session.user.id = token.id as string; 
        session.user.name = token.name as string;
        session.user.email = token.email! as string;
        session.user.image = token.picture as string;
```

**Comment by AyumuOgasawara** [comment]
ビルド成功後に`npm run start`を実行すると以下のようなエラーが出た。

``` sh
[auth][error] UntrustedHost: Host must be trusted. URL was: http://localhost:3000/api/auth/session. Read more at https://errors.authjs.dev#untrustedhost
    at /Users/ayumu/my-projects/receipt-scanner/.next/server/src/middleware.js:380:53303
    at o6 (/Users/ayumu/my-projects/receipt-scanner/.next/server/src/middleware.js:380:56003)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

調べてみると、AUTH_TRUST_HOST="http://localhost:3000"をしたらいいらしく、envに書いたらうまくいった。
